type: recipe
format_version: 1
maintainers: [dorotat]
loggers: [tensorboard, dllogger, extra]
labels:
  origin: bionemo
  workload_ref: ""
  bionemo_ci_pipeline_id: ""
  bionemo_commit_sha: ""
key_segments:
  domain: domain
  config_name: config
  warmup: warmup
  default_overwrites: False
  extra_overwrites: False
  seed: seed
  max_steps: msteps
  dwnstr_task: dwnstrtask
  val_check_interval: valcheck
  accumulate_grad_batches: accgrad
launchers:
  type:slurm:
    ntasks_per_node: '{gpus}'
  name:dgxa100_dracooci:
    mounts:
      /workspace/bionemo/data: /lustre/fsw/portfolios/healthcareeng/projects/healthcareeng_bionemo/jet/data
spec:
  build: bionemo
  scope: ""
  BIONEMO_HOME: "/workspace/bionemo"
  platforms: [linux/amd64]
  wandb_project_name: ""
  wandb_run_link: ""
  pipeline_label: ""
  warmup: 200
  default_overwrites: "++exp_manager.create_tensorboard_logger=True ++exp_manager.wandb_logger_kwargs.offline=False ++exp_manager.create_wandb_logger=True ++exp_manager.create_checkpoint_callback=False ++exp_manager.resume_if_exists=False"
  extra_overwrites: ""
  script: |-
    cd {BIONEMO_HOME};
    mkdir -p {tensorboard_dir};
    export WANDB_API_KEY=$BIONEMO_WANDB_API_KEY;
    model_tag={model}_{variant}_{config_name}_{dwnstr_task}dwnstr;
    python examples/{domain}/{model}/{variant}.py --config-name {config_name} \
    trainer.num_nodes={nodes} trainer.devices={gpus} trainer.precision={precision} model.micro_batch_size={batch_size} \
    ++trainer.accumulate_grad_batches={accumulate_grad_batches} trainer.val_check_interval={val_check_interval} \
    ++model.seed={seed} trainer.max_steps={max_steps} \
    ++model.dwnstr_task_validation.enabled={dwnstr_task} \
    ++model.seq_length=512 \
    model.data.dataset_path=/workspace/bionemo/data/MegaMolBART/zinc_csv \
    model.data.dataset.train=x_OP_000..175_CL_ \
    model.data.dataset.val=x_OP_000..175_CL_ \
    model.data.dataset.test=x_OP_000..175_CL_ \
    ++model.data.index_mapping_dir={BIONEMO_HOME}/data/index_dir/{config_name} \
    {default_overwrites} {extra_overwrites}  \
    ++exp_manager.exp_dir={tensorboard_dir} \
    ++exp_manager.wandb_logger_kwargs.project={wandb_project_name} \
    ++exp_manager.wandb_logger_kwargs.group=${{model_tag}} \
    ++exp_manager.wandb_logger_kwargs.job_type={pipeline_label} \
    ++exp_manager.wandb_logger_kwargs.name={precision}prec_{batch_size}bs_{nodes}node_{gpus}gpu_{max_steps}s_{val_check_interval}valcheck_{accumulate_grad_batches}accgrad \
    ++create_trainer_metric_callback=True ++trainer_metric_callback_kwargs.log_path={assets_dir} \
    ++logs_dir={logs_dir}
  time_limit: 5400
  artifacts: {}
metrics:
  reduced_train_loss:
    goal: minimize
    tags: [accuracy]
    key: primary
  val_loss:
    goal: minimize
    tags: [accuracy ]
    key: secondary
  val_perplexity:
    goal: maximize
    tags: [ accuracy ]
    key: tertiary
  val_loss_ECE:
    goal: minimize
    tags: [ accuracy ]
    key: 4th
products:
  - nodes: [2]
    gpus: [8]
    precision: [16-mixed]
    products:
      - domain: [molecule]
        dwnstr_task: [False]
        products:
          - variant: [pretrain]
            model: [megamolbart]
            config_name: [pretrain_small_span_aug]
            batch_size: [32]
            max_steps: [10000]
            seed: [42, 44, 1234]
            val_check_interval: [1000]
            accumulate_grad_batches: [1]
tests_spec:
  - logic_type: static
    logic_spec:
      exit_codes:
        - 0
      baselines:
        consumed_samples:
          # (this should be exact)
          operator: eq
          value: 5120000.0
        val_loss:
          # mean +/- 2 * std
          operator: range
          max: 0.189
          min: 0.165
        reduced_train_loss:
          # mean +/- 2 * std
          operator: range
          max: 0.191
          min: 0.148
        grad_norm:
          # mean +/- 2 * std
          operator: range
          max: 0.167
          min: 0.0 # sanity check
        val_character_accuracy:
          # mean +/- 2 * std
          operator: range
          max: 0.94
          min: 0.934
        val_molecular_accuracy:
          # mean +/- 2 * std
          operator: range
          max: 0.176
          min: 0.142
        val_percent_invalid:
          operator: range
          max: 0.218
          min: 0
