run_name: 'MoCo_Local_Test_Tiny'
outdir: /workspace/bionemo/bionemo/model/molecule/moco/models/moco_results
resume: null
ema_resume: null
wandb_params:
  mode: 'disabled'  # disabled, offline, online
  entity: 'clara-discovery'
  group: 'config_demo'
  project: 'MoCo'

data:
  dataset_root: "/workspace/bionemo/data/pyg_geom_drug"
  processed_folder: "processed_tiny" #"processed" #
  batch_size: 4 #16
  inference_batch_size: 5 #16
  num_workers: 4
  remove_hs: False
  select_train_subset: 100

loss:
  use_distance: null #'single' 'triple'
  variables:
    - variable_name: 'x'
      loss_scale: 3.0
      aggregate: 'mean'
      continuous: True
    - variable_name: 'h'
      loss_scale: 0.4
      aggregate: 'mean'
      continuous: False
    - variable_name: 'edge_attr'
      loss_scale: 2.0
      aggregate: 'mean'
      continuous: False

interpolant:
  timesteps: &timesteps 500
  time_type: &time_type "discrete"
  scheduler_type: &scheduler_type "cosine_adaptive"
  sample_time_method: "uniform"
  sample_time_mean: 0
  sample_time_scale: 0.81
  variables:
    - variable_name: 'x' #'pos' #'x'
      interpolant_type: 'continuous_diffusion'
      prior_type: 'gaussian'
      timesteps: *timesteps
      num_classes: 3
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 2.0
      com_free: True
    - variable_name: 'h' #'x' #'h'
      interpolant_type: 'discrete_diffusion'
      prior_type: 'uniform'
      timesteps: *timesteps
      num_classes: 16
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 1.0
    - variable_name: 'edge_attr'
      interpolant_type: 'discrete_diffusion'
      prior_type: 'uniform'
      timesteps: *timesteps
      num_classes: 5
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 1.5
    # - variable_name: 'charge'
    #   interpolant_type: null

  
dynamics:
  model_args: None


train:
  seed: 2024
  batch_size: 800
  gpus: 1 #4
  n_epochs: 1000
  enable_progress_bar: True
  gradient_clip_value: 10.0

#! The below are taken from EQGAT
optimizer:
  type: adamw
  lr: 2.e-4
  weight_decay: 1.e-12
  amsgrad: True

lr_scheduler:
  type: plateau
  factor: 0.75
  patience: 20
  min_lr: 5.e-5
  cooldown: 5
  monitor: train-loss
  interval: epoch
  frequency: 5
