run_name: 'NAME'
outdir: ./moco_results
resume: null
ema_resume: null
wandb_params:
  mode: 'disabled'  # disabled, offline, online
  entity: 'clara-discovery'
  group: 'config_demo'
  project: 'MoCo'

data:
  dataset_root: "/workspace/bionemo/data/pyg_geom_drug"
  processed_folder: "processed_tiny"
  batch_size: 4
  inference_batch_size: 5
  num_workers: 4
  remove_hs: False
  select_train_subset: 100

loss:
  use_distance: null #'single' 'triple'
  loss_scale:
   - x: 3.0
     h: 0.4
     edge_attr: 2.0

interpolants:
  timesteps: &timesteps 500
  time_type: &time_type "discrete"
  scheduler_type: &scheduler_type "cosine_adaptive"
  sample_time_method: "uniform"
  sample_time_mean: 0
  sample_time_scale: 0.81
  variables:
    - variable_name: 'x' #'pos' #'x'
      interpolant_type: 'continuous_diffusion'
      prior_type: 'gaussian'
      timesteps: *timesteps
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 2.0
    - variable_name: 'h' #'x' #'h'
      interpolant_type: 'discrete_diffusion'
      prior_type: 'uniform'
      timesteps: *timesteps
      num_classes: 16
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 1.0
    - variable_name: 'edge_attr'
      interpolant_type: 'discrete_diffusion'
      prior_type: 'uniform'
      timesteps: *timesteps
      num_classes: 5
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 1.5
    # - variable_name: 'charge'
    #   interpolant_type: null

  
dynamics:
  model_args: None


train:
  coordinate_loss_scale: 3.0
  atom_type_los_scale: 0.4
  edge_attr:_loss_scale: 2
  seed: 2024
  batch_size: 800
  gpus: 4
  n_epochs: 1000

#! The below are taken from EQGAT
optimizer:
  type: adamw
  lr: 2.e-4
  weight_decay: 1.e-12
  amsgrad: True

scheduler:
  type: plateau
  factor: 0.75
  patience: 20
  min_lr: 5.e-5
  cooldown: 5