run_name: 'eqgat_test'
outdir: /workspace/bionemo/results/eqgatdiff
resume: null
ema_resume: null
wandb_params:
  mode: 'disabled'  # disabled, offline, online
  entity: 'clara-discovery'
  group: 'danny-testing'
  project: 'MoCo'

data:
  dataset_root: "/workspace/bionemo/data/pyg_geom_drug"
  processed_folder: "processed"
  batch_size: &batch_size 200
  inference_batch_size: 200
  removed_h: False
  data_loader_type: "midi"

loss:
  variables:
    - variable_name: 'x'
      loss_scale: 3.0
      aggregate: 'sum'
      continuous: True
      use_distance: null
    - variable_name: 'h'
      loss_scale: 0.4
      aggregate: 'sum'
      continuous: False
    - variable_name: 'edge_attr'
      loss_scale: 2.0
      aggregate: 'sum'
      continuous: False
    - variable_name: 'charges'
      loss_scale: 0.4
      aggregate: 'sum'
      continuous: False

interpolant:
  timesteps: &timesteps 500
  time_type: &time_type "discrete" #["discrete, "continuous]
  scheduler_type: &scheduler_type "cosine_adaptive" #["cosine_adaptive, "linear"]
  sample_time_method: "uniform" # ["symmetric", "uniform", "stab_mode", "logit_normal", "beta"]
  sample_time_mean: 0 # Used in stab_mode and logit_normal
  sample_time_scale: 0.81 # Used in stab_mode and logit_normal
  global_variable_name: 'h' # variable that is specficed below to be used for sampling time and loss sampling
  variables:
    - variable_name: 'x' 
      interpolant_type: 'continuous_diffusion' #["continuous_diffusion", "continuous_flow_matching"]
      diffusion_type: 'vdm'
      prior_type: 'gaussian'
      timesteps: *timesteps
      num_classes: 3
      scheduler_type: *scheduler_type
      scheduler_cut: False
      time_type: *time_type
      nu: 2.5
      com_free: True
    - variable_name: 'h'
      interpolant_type: 'discrete_diffusion' #["discrete_diffusion", "discrete_flow_matching"]
      prior_type: 'custom' #['uniform', 'mask', 'custom']
      custom_prior: '/workspace/bionemo/data/pyg_geom_drug/processed/train_types_h.npy'
      timesteps: *timesteps
      num_classes: &num_atoms 16
      scheduler_type: *scheduler_type
      scheduler_cut: False
      time_type: *time_type
      nu: 1.0
    - variable_name: 'edge_attr'
      interpolant_type: 'discrete_diffusion' #["discrete_diffusion", "discrete_flow_matching"]
      prior_type: 'custom'
      custom_prior: '/workspace/bionemo/data/pyg_geom_drug/processed/train_bond_types_h.npy'
      timesteps: *timesteps
      num_classes: 5
      scheduler_type: *scheduler_type
      scheduler_cut: False
      time_type: *time_type
      nu: 1.5
    - variable_name: 'charges'
      interpolant_type: 'discrete_diffusion' #["discrete_diffusion", "discrete_flow_matching"]
      prior_type: 'custom'
      custom_prior: '/workspace/bionemo/data/pyg_geom_drug/processed/train_charges_prior.npy' #! had to manually create the marginal (h_prior*charge_h_prior[:, None]).sum(0)
      timesteps: *timesteps
      scheduler_type: *scheduler_type
      scheduler_cut: False
      time_type: *time_type
      nu: 1.0
      concat: 'h'
      num_classes: 6
      offset: 2

  
dynamics:
  model_name: "eqgat"
  model_args:
    hn_dim: [256, 256]
    num_layers: 12
    use_cross_product: False
    num_atom_features: 22 # *num_atoms # + *num_charges
    num_bond_types: 5
    edge_dim: 128
    vector_aggr: "mean"
    fully_connected: True
    recompute_edge_attributes: True
    edge_mp: False
    context_mapping: False
    num_context_features: 0
    bond_prediction: False
    coords_param: data
  wrapper_args:
    timesteps: *timesteps
    time_type: *time_type

self_conditioning:
  name: "base"
  variables:
    - variable_name: h
      hidden_dims: 32
      fuse_softmax: True
      vector: False
      clamp_min: null
      clamp_max: null
    - variable_name: charges
      hidden_dims: 16
      fuse_softmax: True
      vector: False
      clamp_min: null
      clamp_max: null

    - variable_name: edge_attr
      hidden_dims: 16
      fuse_softmax: True
      vector: False
      clamp_min: null
      clamp_max: null

    - variable_name: x
      hidden_dims: 1
      fuse_softmax: False
      vector: True
      clamp_min: -100
      clamp_max: 100

sample:
  node_distribution: "/workspace/bionemo/data/pyg_geom_drug/processed/train_n_h.pickle" # null

train:
  seed: 42
  gpus: 4
  n_epochs: 800
  enable_progress_bar: True
  gradient_clip_value: 10.0
  log_freq: 50
  val_freq: 5
  checkpoint_monitor: mol_stable
  checkpoint_monitor_mode: max
  checkpoint_every_n_train_steps: 500

evaluation:
  batch_size: 100
  n_molecules: 250
  timesteps: *timesteps

optimizer:
  type: adamw
  lr: 2.e-4
  weight_decay: 1.e-12
  amsgrad: True

lr_scheduler:
  type: plateau
  factor: 0.75
  patience: 50
  min_lr: 5.e-5
  cooldown: 0
  monitor: val/loss
  interval: epoch
  frequency: 5 #not in config but this is the default
