run_name: 'MoCo_Local_Test'
outdir: /workspace/bionemo/bionemo/model/molecule/moco/results
resume: null
ema_resume: null
wandb_params:
  mode: 'online'  # disabled, offline, online
  entity: 'clara-discovery'
  group: 'testing'
  project: 'MoCo'

data:
  dataset_root: "/workspace/bionemo/data/pyg_geom_drug"
  processed_folder: "processed" #_tiny" #"processed" #
  batch_size: 25 #16
  inference_batch_size: 25 #16
  num_workers: 12 #4
  remove_hs: False
  select_train_subset: 100

loss:
  use_distance: null #'single' 'triple'
  variables:
    - variable_name: 'x'
      loss_scale: 3.0
      aggregate: 'sum'
      continuous: True
    - variable_name: 'h'
      loss_scale: 0.4
      aggregate: 'sum'
      continuous: False
    - variable_name: 'edge_attr'
      loss_scale: 2.0
      aggregate: 'sum'
      continuous: False

interpolant:
  timesteps: &timesteps 500
  time_type: &time_type "discrete" #["discrete, "continuous]
  scheduler_type: &scheduler_type "cosine_adaptive" #["cosine_adaptive, "linear"]
  sample_time_method: "uniform" # ["symmetric", "uniform", "stab_mode", "logit_normal"]
  sample_time_mean: 0 # Used in stab_mode and logit_normal
  sample_time_scale: 0.81 # Used in stab_mode and logit_normal
  global_variable_name: 'h' # variable that is specficed below to be used for sampling time and loss sampling
  variables:
    - variable_name: 'x' 
      interpolant_type: 'continuous_diffusion' #["continuous_diffusion", "continuous_flow_matching"]
      prior_type: 'gaussian'
      timesteps: *timesteps
      num_classes: 3
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 2.5
      com_free: True
    - variable_name: 'h'
      interpolant_type: 'discrete_diffusion' #["discrete_diffusion", "discrete_flow_matching"]
      prior_type: 'custom' #['uniform', 'mask', 'custom']
      custom_prior: '/workspace/bionemo/data/pyg_geom_drug/processed/train_types_h.npy'
      timesteps: *timesteps
      num_classes: 16 # if using masking the system will increase by 1 automatically
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 1.0
    - variable_name: 'edge_attr'
      interpolant_type: 'discrete_diffusion' #["discrete_diffusion", "discrete_flow_matching"]
      prior_type: 'custom'
      custom_prior: '/workspace/bionemo/data/pyg_geom_drug/processed/train_bond_types_h.npy'
      timesteps: *timesteps
      num_classes: 5
      scheduler_type: *scheduler_type
      time_type: *time_type
      nu: 1.5 
    # - variable_name: 'charge'
    #   interpolant_type: null
    #   concat: 'h'

  
dynamics:
  model_args: None

sample:
  node_distribution: "/workspace/bionemo/data/pyg_geom_drug/processed/train_n_h.pickle" # null

train:
  seed: 42
  # batch_size: 800
  gpus: 1 #4
  n_epochs: 1000
  enable_progress_bar: True
  gradient_clip_value: 10.0

#! The below are taken from EQGAT
optimizer:
  type: adamw
  lr: 2.e-4
  weight_decay: 1.e-12
  amsgrad: True

lr_scheduler:
  type: plateau
  factor: 0.75
  patience: 50
  min_lr: 5.e-5
  cooldown: 0
  monitor: val/loss
  interval: epoch
  frequency: 5 #not in config but this is default
